#!/bin/bash
servicename=attestation-sync
servicefile=/etc/systemd/system/ncubed-$servicename.service
if [ -L $servicefile ]; then
  rm $servicefile
fi
ln -s /opt/ncubed/$servicename.service/ncubed-$servicename.service $servicefile
systemctl start ncubed-$servicename
systemctl enable ncubed-$servicename
