---
all:
  hosts:
  children:
    BRANCH:
      hosts:
        'fd71::1':
          clusternode: 0
    DATACENTER:
      hosts:
  vars:
    ansible_user: '{{ lookup("env", "ANSIBLE_USER") }}'
    ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'