- name: Update system
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: update apt
      ansible.builtin.command: apt update

    - name: install snmpd
      ansible.builtin.command: apt -y install snmpd

    - name: Copy using inline content
      ansible.builtin.copy:
        src: ./templates/etc/snmp/snmpd.conf
        dest: /etc/snmp/snmpd.conf

    - name: Start SNMP Service
      service:
        name: snmpd
        state: started
        enabled: yes
