- name: Update system
  hosts: all
  become: yes
  gather_facts: no
  serial:
    - 1
    - 5
    - 30
  order: sorted

  tasks:
    - name: get active wan namespace
      ansible.builtin.shell: 'ip -br addr | grep wg_ | grep -o "WAN[0-9]"'
      register: interface

    - name: update apt
      ansible.builtin.command: ip netns exec ns_{{interface.stdout}} apt update

    - name: install snmpd
      ansible.builtin.command: ip netns exec ns_{{interface.stdout}} apt -y install snmpd

    - name: Copy using inline content
      ansible.builtin.copy:
        src: ./templates/etc/snmp/snmpd.conf
        dest: /etc/snmp/snmpd.conf

    - name: Start SNMP Service
      service:
        name: snmpd
        state: restarted
        enabled: yes

    - name: populate system info
      ansible.builtin.shell: |
        printf -- "---
        platform: $(sudo /usr/sbin/dmidecode -s system-family)
        serial: $(sudo /usr/sbin/dmidecode -s system-serial-number)
        " > /opt/ncubed/system.yaml