---
- name: Update ncubed services
  hosts: all
  become: yes
  gather_facts: no

  tasks:
  - set_fact:
      UPDATE: 20220419-1344

  - name: copy ncubed update
    local_action: ansible.builtin.command sshpass -p {{ ansible_password }} rsync -arvzh /opt/ncubed/updates/{{ UPDATE }} {{ ansible_user }}@[{{ inventory_hostname }}]:/tmp/ncubed_update

  - name: install update
    ansible.builtin.command: /bin/bash /tmp/ncubed_update/{{ UPDATE }}/install.sh