---
- name: Update ncubed services
  hosts: all
  become: yes
  gather_facts: no

  tasks:
  - set_fact:
      UPDATE: 20220419-1344
      TMP_FOLDER: /tmp/ncubed_update

  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: "{{ TMP_FOLDER }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'
      recurse: yes
      state: directory

  - name: copy ncubed update
    local_action: ansible.builtin.command sshpass -p {{ ansible_password }} rsync -arvzh /opt/ncubed/updates/{{ UPDATE }} {{ ansible_user }}@[{{ inventory_hostname }}]:{{ TMP_FOLDER }}

  - name: install update
    ansible.builtin.command: /bin/bash {{ TMP_FOLDER }}/{{ UPDATE }}/install.sh