---
- name: Update ncubed services
  hosts: all
  become: yes
  gather_facts: no

  tasks:
  - set_fact:
      UPDATE: 20220419-1344

  - name: copy ncubed upddate
    copy:
      src: /opt/ncubed/updates/{{ UPDATE }}/
      dest: /tmp/ncubed_update
      directory_mode:

  - name: install update
    ansible.builtin.command: /bin/bash /tmp/ncubed_update/install.sh